/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataGrid: typeof import('./src/components/DataGrid.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FeatureHeader: typeof import('./src/components/FeatureHeader.vue')['default']
    FormTable: typeof import('./src/components/FormTable.vue')['default']
    FormTableInput: typeof import('./src/components/FormTableInput.vue')['default']
    FormTableInputSelect: typeof import('./src/components/FormTableInputSelect.vue')['default']
    FormTableInputText: typeof import('./src/components/FormTableInputText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
